# kamibotSocketUrl: "wss://kamibot.kami.live/minecraftForge/ws" # URL to connect to the Kamibot server (string)
# uuid: -1 # Randomly generated UUID (int)
# enableVerboseLogging: false # Enable verbose logging (boolean)