name: Release

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set output tag
        id: set_output_tag
        run: echo "::set-output name=new_tag::${{ steps.tag_version.outputs.new_tag }}"

  build:
    runs-on: ubuntu-latest
    needs: bump-version
    strategy:
      matrix:
        minecraft-version: ["1.20", "1.21"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "21"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew shadowJar -PreleaseVersion=${{ needs.bump-version.outputs.new_tag }} -PminecraftVersion=${{ matrix.minecraft-version }}

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.bump-version.outputs.new_tag }}
          release_name: Release ${{ needs.bump-version.outputs.new_tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/Kamibot-Remote-Paper_${{ matrix.minecraft-version }}_${{ needs.bump-version.outputs.new_tag }}.jar
          asset_name: Kamibot-Remote-Paper_${{ matrix.minecraft-version }}_${{ needs.bump-version.outputs.new_tag }}.jar
          asset_content_type: application/zip
          body: ${{ steps.tag_version.outputs.changelog }}

          